FROM eclipse-temurin:17-jdk-jammy AS base

FROM base AS builder
WORKDIR /app
COPY pom.xml .
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY src ./src  
RUN ./mvnw clean package -DskipTests

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
